os: linux
dist: bionic
language: python
jobs:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
install:
  - pip install -r requirements-dev.txt
  - pip install codecov
script: py.test --cov=monitorrent --cov-report html --html=report.html -rw tests
after_success:
  - coveralls
  - codecov
